# Change these first
owner: Nordgedanken # Your GitHub organization or username
repo: status-nordgedanken-dev # Your GitHub repository name

# Add your sites here
sites:
  - name: Fluffychat Fdroid Stable
    url: https://fdroid.fluffychat.im
  - name: Fluffychat Fdroid Nightly
    url: https://nightly.fdroid.fluffychat.im/
  - name: Matrix Server
    url: https://matrix.nordgedanken.dev
  - name: Funkwhale
    url: https://audio.nordgedanken.dev

status-website:
  cname: status.nordgedanken.dev
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Nordgedanken
  introTitle: "**Upptime** Nordgedanken"
  introMessage: Status of Nordgedanken stuff
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
workflowSchedule:
  graphs: "*/33 * * * *"
  responseTime: "*/22 * * * *"
  staticSite: "*/11 * * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
